package it.fastrade.app;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.text.InputType;
import android.text.TextUtils;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private final int BG=Color.rgb(3,12,20), BG2=Color.rgb(4,18,29), SURFACE=Color.rgb(8,25,38), SURFACE2=Color.rgb(14,34,50), BLUE=Color.rgb(25,135,255), BLUE2=Color.rgb(4,104,228), CYAN=Color.rgb(26,211,255), GREEN=Color.rgb(24,222,151), RED=Color.rgb(244,67,83), TEXT=Color.rgb(246,249,253), MUTED=Color.rgb(149,169,190), LINE=Color.rgb(31,63,88), DARKGREEN=Color.rgb(3,81,57), GOLD=Color.rgb(255,190,39), PURPLE=Color.rgb(117,75,255);
    private final DecimalFormat money=new DecimalFormat("€ #,##0.00"), one=new DecimalFormat("0.0"), pct=new DecimalFormat("0.0%");
    private TradeDbHelper db; private SharedPreferences prefs;
    private LinearLayout root, header, content, nav; private ScrollView scroll;
    private int journalFilter=0, dashDays=30, bankDays=30, bankTab=0, statsTab=0;
    private static final int REQ_EXPORT_CSV=7101, REQ_BACKUP=7102, REQ_RESTORE=7103;
    private final ArrayList<NavItem> navItems=new ArrayList<>();
    private static final String[] SPORTS={"Calcio","Tennis","Basket","Altro"};
    private static final String[] MARKETS={"Over/Under 0.5","Over/Under 1.5","Over/Under 2.5","Over/Under 3.5","BTTS","1X2","Risultato esatto","Lay the Draw","Banca risultato esatto","Altro"};
    private static final String[] DEFAULT_STRATEGIES={"LTD","SPLIT UNDER","SPLIT OVER LINEA 1","SPLIT OVER LINEA 2","BANCA 1","BANCA 2","OVER 0,5 PT","PUNTA 1","PUNTA 2","PUNTA RIS. ESATTO","BTTS","SNIPE RIS. ESATTO","TENNIS"};

    @Override protected void onCreate(Bundle b){
        super.onCreate(b);
        getWindow().setStatusBarColor(BG); getWindow().setNavigationBarColor(BG);
        db=new TradeDbHelper(this); prefs=getSharedPreferences("fastrade_prefs",MODE_PRIVATE);
        buildShell(); showDashboard();
    }

    private void buildShell(){
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackground(verticalGradient(BG,BG2));
        header=new LinearLayout(this); header.setOrientation(LinearLayout.VERTICAL); root.addView(header,new LinearLayout.LayoutParams(-1,-2));
        scroll=new ScrollView(this); scroll.setFillViewport(true); scroll.setOverScrollMode(View.OVER_SCROLL_NEVER);
        content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(dp(16),dp(4),dp(16),dp(22)); scroll.addView(content); root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=row(); nav.setGravity(Gravity.CENTER); nav.setBackgroundColor(Color.rgb(6,20,31)); nav.setPadding(dp(6),dp(2),dp(6),dp(2));
        addNav("⌂","Home",0,()->showDashboard()); addNav("＋","Nuova",1,()->showNewOperation()); addNav("▤","Diario",2,()->showJournal()); addNav("▥","Statistiche",3,()->showStats()); addNav("●","Bankroll",4,()->showBankroll());
        root.addView(nav,new LinearLayout.LayoutParams(-1,dp(66)));
        root.setOnApplyWindowInsetsListener((v,insets)->{int top=insets.getSystemWindowInsetTop();int bottom=insets.getSystemWindowInsetBottom();root.setPadding(0,top,0,0);LinearLayout.LayoutParams lp=(LinearLayout.LayoutParams)nav.getLayoutParams();lp.height=dp(66)+bottom;nav.setLayoutParams(lp);nav.setPadding(dp(6),dp(2),dp(6),bottom+dp(2));return insets;});
        setContentView(root); root.requestApplyInsets();
    }

    private void renderHeader(String title,int navIndex){
        header.removeAllViews();
        if(navIndex==0){
            LinearLayout bar=row(); bar.setGravity(Gravity.CENTER_VERTICAL); bar.setPadding(dp(18),dp(9),dp(18),dp(8));
            ImageView logo=new ImageView(this); logo.setImageResource(getResources().getIdentifier("ic_launcher","mipmap",getPackageName())); logo.setScaleType(ImageView.ScaleType.CENTER_CROP); bar.addView(logo,new LinearLayout.LayoutParams(dp(50),dp(50)));
            LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setPadding(dp(10),0,0,0);TextView n=text("FasTrade",25,TEXT,true);brand.addView(n);TextView s=text("SPORTS TRADING",9,BLUE,true);s.setLetterSpacing(.22f);brand.addView(s);bar.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
            TextView gear=text("⚙",22,CYAN,false);gear.setGravity(Gravity.CENTER);gear.setBackground(round(Color.argb(40,25,135,255),18,Color.argb(70,25,135,255)));gear.setOnClickListener(v->showToolsScreen());bar.addView(gear,new LinearLayout.LayoutParams(dp(42),dp(42)));header.addView(bar);
            TextView pay=text("DISCIPLINA  |  STRATEGIA  |  RISULTATI",8,Color.rgb(164,191,215),false);pay.setLetterSpacing(.12f);pay.setPadding(dp(78),0,0,dp(8));header.addView(pay);
        }else if(navIndex==-1){
            LinearLayout bar=row();bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(16),dp(9),dp(16),dp(7));TextView back=text("‹",34,TEXT,false);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->showDashboard());bar.addView(back,new LinearLayout.LayoutParams(dp(42),dp(46)));TextView t=text("FasTrade",18,TEXT,true);t.setGravity(Gravity.CENTER);bar.addView(t,new LinearLayout.LayoutParams(0,dp(46),1));TextView empty=text("",20,TEXT,false);bar.addView(empty,new LinearLayout.LayoutParams(dp(42),dp(46)));header.addView(bar);
        }else{
            LinearLayout bar=row();bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(14),dp(8),dp(14),dp(6));
            TextView back=text("‹",34,TEXT,false);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->showDashboard());bar.addView(back,new LinearLayout.LayoutParams(dp(42),dp(46)));
            TextView t=text(title,18,TEXT,true);t.setGravity(Gravity.CENTER);bar.addView(t,new LinearLayout.LayoutParams(0,dp(46),1));
            TextView spacer=text(navIndex==3?"⌁":"",20,CYAN,false);spacer.setGravity(Gravity.CENTER);bar.addView(spacer,new LinearLayout.LayoutParams(dp(42),dp(46)));header.addView(bar);
        }
    }

    private void addNav(String icon,String label,int index,Runnable r){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);TextView i=text(icon,18,MUTED,true),t=text(label,9,MUTED,false);i.setGravity(Gravity.CENTER);t.setGravity(Gravity.CENTER);box.addView(i,new LinearLayout.LayoutParams(-1,dp(27)));box.addView(t,new LinearLayout.LayoutParams(-1,dp(20)));box.setOnClickListener(v->r.run());nav.addView(box,new LinearLayout.LayoutParams(0,-1,1));navItems.add(new NavItem(box,i,t,index));}
    private void selectNav(int index){for(NavItem n:navItems){int c=n.index==index?BLUE:MUTED;n.icon.setTextColor(c);n.label.setTextColor(c);n.icon.setScaleX(n.index==index?1.08f:1f);n.icon.setScaleY(n.index==index?1.08f:1f);}}
    private void page(String title,int navIndex){content.removeAllViews();scroll.scrollTo(0,0);selectNav(navIndex);renderHeader(title,navIndex);}

    private void showDashboard(){page("",0);Stats s=stats();
        content.addView(new HeroBankCard(this,s),new LinearLayout.LayoutParams(-1,dp(155)));
        LinearLayout kr=row();kr.addView(kpiSpark("Net Profit",money.format(s.netProfit),s.netProfit>=0?GREEN:RED,0),wp());kr.addView(kpiSpark("ROI",s.totalStake==0?"0,0%":pct.format(s.roi),s.roi>=0?GREEN:RED,1),wp());kr.addView(kpiSpark("Win Rate",s.totalTrades==0?"0,0%":pct.format(s.winPct),CYAN,2),wp());content.addView(kr);
        LinearLayout sh=row();sh.setGravity(Gravity.CENTER_VERTICAL);sh.addView(section("Andamento Bankroll"),new LinearLayout.LayoutParams(0,-2,1));LinearLayout chips=row();chips.addView(chip("7G",dashDays==7,v->{dashDays=7;showDashboard();}));chips.addView(chip("1M",dashDays==30,v->{dashDays=30;showDashboard();}));chips.addView(chip("3M",dashDays==90,v->{dashDays=90;showDashboard();}));chips.addView(chip("1A",dashDays==365,v->{dashDays=365;showDashboard();}));sh.addView(chips);content.addView(sh);
        LinearLayout chartCard=card(Color.rgb(4,21,32));chartCard.setPadding(dp(8),dp(5),dp(8),dp(3));chartCard.addView(new BankrollChart(this,bankrollSeries(s.startingBank,dashDays),dashDays,true),new LinearLayout.LayoutParams(-1,dp(176)));content.addView(chartCard);
        LinearLayout todayHead=row();todayHead.setGravity(Gravity.CENTER_VERTICAL);todayHead.addView(section("Oggi"),new LinearLayout.LayoutParams(0,-2,1));todayHead.addView(text(new SimpleDateFormat("d MMM yyyy",Locale.ITALY).format(new Date()),10,MUTED,false));content.addView(todayHead);
        double td=todayProfit();LinearLayout tr=row();tr.addView(kpi("Profitto Giornaliero",money.format(td),td>=0?GREEN:RED),wp());tr.addView(kpi("Target 1%",money.format(s.currentBank*.01),GOLD),wp());tr.addView(kpi("Operazioni",String.valueOf(todayTrades()),BLUE),wp());content.addView(tr);
        if(s.startingBank==0)content.addView(action("IMPOSTA STARTING BANK",BLUE,v->askStartingBank()));
    }

    private void showNewOperation(){page("Nuova Operazione",1);LinearLayout tabs=row();tabs.addView(tab("Operazione",true,null),wp());tabs.addView(tab("Calcolo Stake",false,v->toast("Il calcolo stake è integrato nell'operazione.")),wp());content.addView(tabs);
        EditText date=input(false,"Data");date.setText(new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY).format(new Date()));content.addView(field("Data",date));Spinner sport=spinner(SPORTS);content.addView(field("Sport",sport));EditText match=input(false,"Es. Juventus - Lazio");content.addView(field("Match",match));Spinner market=spinner(MARKETS);content.addView(field("Mercato",market));List<String> sn=getStrategies();Spinner strategy=spinner(sn.toArray(new String[0]));content.addView(field("Strategia",strategy));
        LinearLayout mini=row();EditText minute=input(true,"45");EditText tranche=input(true,"1");EditText stakePct=input(true,"2,0");mini.addView(fieldMini("Minuto ingresso",minute),wp());mini.addView(fieldMini("Tranche",tranche),wp());mini.addView(fieldMini("Stake %",stakePct),wp());content.addView(mini);
        TextView stakeCard=text("Stake € (calcolato)\n"+money.format(0),17,GREEN,true);stakeCard.setGravity(Gravity.CENTER);stakeCard.setPadding(dp(10),dp(8),dp(10),dp(8));stakeCard.setBackground(horizontalGradient(Color.rgb(1,89,61),Color.rgb(2,55,42),14,GREEN));content.addView(stakeCard,new LinearLayout.LayoutParams(-1,dp(64)));
        EditText odds=input(true,"1,75");content.addView(field("Quota ingresso",odds));final boolean[] win={true};LinearLayout wr=row();Button wb=smallButton("WIN",GREEN),lb=smallButton("LOSE",SURFACE2);wr.addView(wb,wp());wr.addView(lb,wp());wb.setOnClickListener(v->{win[0]=true;wb.setBackground(horizontalGradient(GREEN,Color.rgb(1,162,103),10,0));lb.setBackground(round(SURFACE2,10,LINE));});lb.setOnClickListener(v->{win[0]=false;lb.setBackground(horizontalGradient(RED,Color.rgb(171,38,55),10,0));wb.setBackground(round(SURFACE2,10,LINE));});content.addView(field("Risultato",wr));
        EditText pl=input(true,"Es. 18,75");content.addView(field("Profit / Loss €",pl));EditText rating=input(false,"A / B / C");content.addView(field("Voto operazione",rating));EditText notes=input(false,"Aggiungi una nota...");notes.setMinHeight(dp(58));content.addView(field("Note (opzionale)",notes));
        Runnable calc=()->{Stats st=stats();double p=parse(stakePct.getText().toString());stakeCard.setText("Stake € (calcolato)\n"+money.format(st.currentBank*p/100d));};stakePct.setOnFocusChangeListener((v,f)->{if(!f)calc.run();});
        content.addView(action("SALVA OPERAZIONE",BLUE,v->{double result=parse(pl.getText().toString());if(result!=0)result=win[0]?Math.abs(result):-Math.abs(result);Stats st=stats();double p=parse(stakePct.getText().toString());TradeDbHelper.Operation o=new TradeDbHelper.Operation();o.date=date.getText().toString().trim();o.match=match.getText().toString().trim();o.sport=String.valueOf(sport.getSelectedItem());o.marketType=String.valueOf(market.getSelectedItem());o.strategy=String.valueOf(strategy.getSelectedItem());o.market=o.strategy;o.minute=minute.getText().toString().trim();o.tranche=tranche.getText().toString().trim();o.stakePct=p;o.stakeEur=st.currentBank*p/100d;o.odds=parse(odds.getText().toString());o.result=result;o.rating=rating.getText().toString().trim();o.notes=notes.getText().toString().trim();db.addOperation(o);toast("Operazione salvata");showJournal();}));
    }

    private void showJournal(){page("Diario Operazioni",2);LinearLayout filters=row();String[] fs={"Tutte","Oggi","Settimana","Mese"};for(int i=0;i<fs.length;i++){final int idx=i;filters.addView(chip(fs[i],journalFilter==i,v->{journalFilter=idx;showJournal();}),wp());}content.addView(filters);List<TradeDbHelper.Operation> ops=filteredOps();if(ops.isEmpty()){content.addView(empty("Nessuna operazione in questo periodo."));return;}String last="";for(TradeDbHelper.Operation o:ops){if(!o.date.equals(last)){LinearLayout dh=row();dh.setPadding(dp(4),dp(12),dp(4),dp(5));dh.addView(text(o.date,12,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));double dt=dayTotal(o.date);dh.addView(text(sign(dt)+money.format(Math.abs(dt)),12,dt>=0?GREEN:RED,true));content.addView(dh);last=o.date;}LinearLayout c=card(Color.rgb(5,23,35));c.setPadding(dp(13),dp(10),dp(13),dp(10));LinearLayout top=row();top.setGravity(Gravity.CENTER_VERTICAL);TextView sportIcon=text(o.sport.equalsIgnoreCase("Tennis")?"◉":"⚽",18,Color.rgb(208,222,235),false);sportIcon.setGravity(Gravity.CENTER);top.addView(sportIcon,new LinearLayout.LayoutParams(dp(34),dp(44)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.addView(text(o.match.isEmpty()?"—":o.match,13,TEXT,true));String meta=(o.marketType.isEmpty()?o.market:o.marketType)+" | "+(o.strategy.isEmpty()?o.market:o.strategy);info.addView(text(meta,9,MUTED,false));String meta2=(o.minute.isEmpty()?"":o.minute+"' | ")+(o.odds>0?"@"+one.format(o.odds)+" | ":"")+money.format(o.stakeEur);info.addView(text(meta2,9,Color.rgb(145,171,196),false));top.addView(info,new LinearLayout.LayoutParams(0,-2,1));LinearLayout rhs=new LinearLayout(this);rhs.setOrientation(LinearLayout.VERTICAL);rhs.setGravity(Gravity.RIGHT);TextView badge=text(o.result>=0?"WIN":"LOSE",10,Color.WHITE,true);badge.setGravity(Gravity.CENTER);badge.setBackground(round(o.result>=0?Color.rgb(3,126,82):Color.rgb(187,40,54),9,0));rhs.addView(badge,new LinearLayout.LayoutParams(dp(60),dp(28)));TextView pv=text(sign(o.result)+money.format(Math.abs(o.result)),13,o.result>=0?GREEN:RED,true);pv.setGravity(Gravity.RIGHT);pv.setPadding(0,dp(5),0,0);rhs.addView(pv);top.addView(rhs);c.addView(top);c.setOnLongClickListener(v->{confirmDelete(o.id);return true;});content.addView(c);}}

    private void showStats(){page("Statistiche",3);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tabs=row();String[] names={"Panoramica","Strategie","Sport","Mese","Personalizzato"};for(int i=0;i<names.length;i++){final int x=i;tabs.addView(tab(names[i],statsTab==i,v->{statsTab=x;showStats();}),new LinearLayout.LayoutParams(dp(i==4?112:88),-2));}hs.addView(tabs);content.addView(hs);
        if(statsTab==0){showAnalyticsOverview();return;}
        List<TradeDbHelper.Operation> ops=db.allOperations();Map<String,SS> map=new LinkedHashMap<>();SimpleDateFormat in=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY),out=new SimpleDateFormat("MMM yyyy",Locale.ITALY);for(TradeDbHelper.Operation o:ops){if(isMovement(o))continue;String k;if(statsTab==2)k=o.sport.isEmpty()?"Altro":o.sport;else if(statsTab==3){try{k=out.format(in.parse(o.date));}catch(Exception e){k="Senza data";}}else k=o.strategy.isEmpty()?o.market:o.strategy;SS x=map.get(k);if(x==null){x=new SS();map.put(k,x);}x.op++;if(o.result>0)x.win++;else if(o.result<0)x.lose++;x.profit+=o.result;x.stake+=o.stakeEur;}if(map.isEmpty()){content.addView(empty("Registra alcune operazioni per vedere le statistiche."));return;}
        LinearLayout table=card(Color.rgb(4,20,31));LinearLayout hd=row();hd.addView(cell(statsTab==2?"Sport":statsTab==3?"Mese":"Strategia",9,MUTED,true,2.0f));hd.addView(cell("Op.",9,MUTED,true,.7f));hd.addView(cell("Win",9,MUTED,true,.7f));hd.addView(cell("Lose",9,MUTED,true,.7f));hd.addView(cell("Win %",9,MUTED,true,1f));hd.addView(cell("Profit",9,MUTED,true,1.3f));table.addView(hd);for(Map.Entry<String,SS> e:map.entrySet()){SS x=e.getValue();LinearLayout rr=row();rr.addView(cell(e.getKey(),10,TEXT,true,2.0f));rr.addView(cell(String.valueOf(x.op),10,TEXT,false,.7f));rr.addView(cell(String.valueOf(x.win),10,GREEN,false,.7f));rr.addView(cell(String.valueOf(x.lose),10,TEXT,false,.7f));rr.addView(cell(x.op==0?"0%":one.format(100d*x.win/x.op)+"%",10,TEXT,false,1f));rr.addView(cell(money.format(x.profit),10,x.profit>=0?GREEN:RED,true,1.3f));table.addView(rr);}content.addView(table);
        content.addView(section("Distribuzione Profitto"));content.addView(new DonutCard(this,map),new LinearLayout.LayoutParams(-1,dp(210)));
    }

    private void showAnalyticsOverview(){Stats s=stats();LinearLayout k=row();k.addView(kpiSpark("Profitto Totale",money.format(s.netProfit),s.netProfit>=0?GREEN:RED,0),wp());k.addView(kpiSpark("ROI",s.totalStake==0?"0,0%":pct.format(s.roi),GREEN,1),wp());k.addView(kpiSpark("Win Rate",s.totalTrades==0?"0,0%":pct.format(s.winPct),CYAN,2),wp());content.addView(k);
        LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);h.addView(section("Andamento Profitto"),new LinearLayout.LayoutParams(0,-2,1));LinearLayout chips=row();chips.addView(chip("7G",dashDays==7,v->{dashDays=7;showStats();}));chips.addView(chip("1M",dashDays==30,v->{dashDays=30;showStats();}));chips.addView(chip("3M",dashDays==90,v->{dashDays=90;showStats();}));chips.addView(chip("1A",dashDays==365,v->{dashDays=365;showStats();}));h.addView(chips);content.addView(h);
        LinearLayout lineCard=card(Color.rgb(4,20,31));lineCard.setPadding(dp(8),dp(6),dp(8),dp(4));lineCard.addView(new DualLineChart(this,bankrollSeries(s.startingBank,dashDays),profitSeries(dashDays),dashDays),new LinearLayout.LayoutParams(-1,dp(190)));content.addView(lineCard);
        content.addView(section("Profitto per Strategia"));Map<String,SS> byStr=strategyMap();content.addView(new ProfitBars(this,byStr),new LinearLayout.LayoutParams(-1,dp(Math.max(170,Math.min(320,70+byStr.size()*30)))));
        content.addView(section("Distribuzione Profitto"));content.addView(new DonutCard(this,byStr),new LinearLayout.LayoutParams(-1,dp(210)));
    }

    private void showBankroll(){page("Bankroll",4);Stats s=stats();LinearLayout r=row();r.addView(kpi("Starting Bank",money.format(s.startingBank),TEXT),wp());r.addView(kpi("Current Bank",money.format(s.currentBank),GREEN),wp());content.addView(r);LinearLayout r2=row();r2.addView(kpi("Depositi",money.format(s.deposits),BLUE),wp());r2.addView(kpi("Prelievi",money.format(Math.abs(s.withdrawals)),TEXT),wp());r2.addView(kpi("Net Profit",money.format(s.netProfit),s.netProfit>=0?GREEN:RED),wp());content.addView(r2);
        LinearLayout tabs=row();tabs.addView(tab("Grafico",bankTab==0,v->{bankTab=0;showBankroll();}),wp());tabs.addView(tab("Movimenti",bankTab==1,v->{bankTab=1;showBankroll();}),wp());content.addView(tabs);
        if(bankTab==0){LinearLayout range=row();range.setGravity(Gravity.RIGHT);range.addView(chip("7G",bankDays==7,v->{bankDays=7;showBankroll();}));range.addView(chip("1M",bankDays==30,v->{bankDays=30;showBankroll();}));range.addView(chip("3M",bankDays==90,v->{bankDays=90;showBankroll();}));range.addView(chip("1A",bankDays==365,v->{bankDays=365;showBankroll();}));content.addView(range);LinearLayout chartCard=card(Color.rgb(4,20,31));chartCard.setPadding(dp(7),dp(5),dp(7),dp(2));chartCard.addView(new BankrollChart(this,bankrollSeries(s.startingBank,bankDays),bankDays,true),new LinearLayout.LayoutParams(-1,dp(205)));content.addView(chartCard);}else{showMovementsList();}
        content.addView(section("Obiettivi"));content.addView(goal("Target Giornaliero 1%",todayProfit(),s.currentBank*.01));content.addView(goal("Target Settimanale 5%",weekProfit(),s.currentBank*.05));content.addView(action("MODIFICA STARTING BANK",BLUE2,v->askStartingBank()));content.addView(action("REGISTRA DEPOSITO / PRELIEVO",GREEN,v->movementDialog()));content.addView(action("GESTIONE STRATEGIE",BLUE,v->showStrategyManager())); }

    private void showMovementsList(){List<TradeDbHelper.Operation> all=db.allOperations();boolean any=false;for(TradeDbHelper.Operation o:all){if(!isMovement(o))continue;any=true;LinearLayout c=card(SURFACE);LinearLayout rr=row();LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.VERTICAL);left.addView(text(o.market.equals("DEPOSIT")?"Deposito":"Prelievo",13,TEXT,true));left.addView(text(o.date,10,MUTED,false));rr.addView(left,new LinearLayout.LayoutParams(0,-2,1));LinearLayout right=new LinearLayout(this);right.setOrientation(LinearLayout.VERTICAL);right.setGravity(Gravity.RIGHT);TextView amt=text((o.result>=0?"+ ":"- ")+money.format(Math.abs(o.result)),13,o.result>=0?GREEN:RED,true);amt.setGravity(Gravity.RIGHT);right.addView(amt);Button del=smallButton("ELIMINA",Color.rgb(145,35,45));del.setOnClickListener(v->confirmDeleteMovement(o.id));right.addView(del,new LinearLayout.LayoutParams(dp(86),dp(36)));rr.addView(right);c.addView(rr);content.addView(c);}if(!any)content.addView(empty("Nessun deposito o prelievo registrato."));}

    private void movementDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(5),dp(18),0);Spinner sp=spinner(new String[]{"Deposito","Prelievo"});EditText amount=input(true,"Importo €");box.addView(field("Tipo",sp));box.addView(field("Importo",amount));new AlertDialog.Builder(this).setTitle("Movimento bankroll").setView(box).setPositiveButton("Salva",(d,w)->{double a=Math.abs(parse(amount.getText().toString()));TradeDbHelper.Operation o=new TradeDbHelper.Operation();o.date=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY).format(new Date());o.market=sp.getSelectedItemPosition()==0?"DEPOSIT":"WITHDRAW";o.strategy=o.market;o.marketType=o.market;o.sport="";o.result=sp.getSelectedItemPosition()==0?a:-a;db.addOperation(o);bankTab=1;showBankroll();}).setNegativeButton("Annulla",null).show();}

    private void showToolsScreen(){page("",-1);LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setGravity(Gravity.CENTER);brand.setPadding(0,dp(18),0,dp(22));ImageView img=new ImageView(this);img.setImageResource(getResources().getIdentifier("ic_launcher","mipmap",getPackageName()));img.setScaleType(ImageView.ScaleType.CENTER_CROP);brand.addView(img,new LinearLayout.LayoutParams(dp(86),dp(86)));TextView logo=text("FasTrade",28,TEXT,true);logo.setGravity(Gravity.CENTER);brand.addView(logo);TextView sub=text("SPORTS TRADING",10,Color.WHITE,true);sub.setLetterSpacing(.22f);sub.setGravity(Gravity.CENTER);brand.addView(sub);TextView pay=text("DISCIPLINA | STRATEGIA | RISULTATI",8,MUTED,false);pay.setGravity(Gravity.CENTER);pay.setPadding(0,dp(10),0,0);brand.addView(pay);content.addView(brand);content.addView(menuRow("⇩","ESPORTA DATI CSV",v->exportCsv()));content.addView(menuRow("☁","BACKUP",v->backupData()));content.addView(menuRow("↻","RIPRISTINO DATI",v->restoreData()));content.addView(menuRow("⚙","IMPOSTAZIONI",v->openAppSettings()));content.addView(new WaveDecoration(this),new LinearLayout.LayoutParams(-1,dp(90)));TextView quote=text("“Il metodo trasforma la disciplina in risultati.”\n\nAntonio Savio Fustolo",13,TEXT,false);quote.setGravity(Gravity.CENTER);quote.setTypeface(Typeface.create("sans",Typeface.ITALIC));quote.setPadding(dp(20),0,dp(20),dp(22));content.addView(quote);}

    private View menuRow(String icon,String label,View.OnClickListener click){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(5),dp(12),dp(5));r.setBackground(horizontalGradient(Color.rgb(9,31,48),Color.rgb(5,23,36),14,LINE));TextView i=text(icon,20,Color.rgb(166,214,243),false);i.setGravity(Gravity.CENTER);r.addView(i,new LinearLayout.LayoutParams(dp(46),dp(50)));TextView t=text(label,12,TEXT,true);r.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));TextView a=text("›",22,MUTED,false);a.setGravity(Gravity.CENTER);r.addView(a,new LinearLayout.LayoutParams(dp(32),dp(50)));r.setOnClickListener(click);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));r.setLayoutParams(lp);return r;}
    private void exportCsv(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"FasTrade_Trades.csv");startActivityForResult(i,REQ_EXPORT_CSV);}
    private void backupData(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,"FasTrade_Backup.db");startActivityForResult(i,REQ_BACKUP);}
    private void restoreData(){new AlertDialog.Builder(this).setTitle("Ripristino dati").setMessage("Il ripristino sostituirà i dati attuali con quelli del backup selezionato.").setPositiveButton("Continua",(d,w)->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ_RESTORE);}).setNegativeButton("Annulla",null).show();}
    private void openAppSettings(){Intent i=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()));startActivity(i);}

    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(resultCode!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{if(requestCode==REQ_EXPORT_CSV)writeCsv(uri);else if(requestCode==REQ_BACKUP)writeBackup(uri);else if(requestCode==REQ_RESTORE)readBackup(uri);}catch(Exception e){toast("Errore: "+e.getMessage());}}
    private void writeCsv(Uri uri)throws Exception{OutputStream os=getContentResolver().openOutputStream(uri);if(os==null)throw new IOException("Impossibile creare il file");BufferedWriter w=new BufferedWriter(new OutputStreamWriter(os,"UTF-8"));w.write('\ufeff');w.write("Data;Sport;Match;Mercato;Strategia;Minuto;Tranche;Stake %;Stake EUR;Quota;Risultato;Voto;Note\n");for(TradeDbHelper.Operation o:db.allOperations()){if(isMovement(o))continue;w.write(csv(o.date)+";"+csv(o.sport)+";"+csv(o.match)+";"+csv(o.marketType)+";"+csv(o.strategy)+";"+csv(o.minute)+";"+csv(o.tranche)+";"+one.format(o.stakePct)+";"+one.format(o.stakeEur)+";"+one.format(o.odds)+";"+one.format(o.result)+";"+csv(o.rating)+";"+csv(o.notes)+"\n");}w.flush();w.close();toast("CSV esportato: apribile con Excel");}
    private String csv(String s){if(s==null)return "";String x=s.replace("\"","\"\"");return "\""+x+"\"";}
    private void writeBackup(Uri uri)throws Exception{db.getWritableDatabase().rawQuery("PRAGMA wal_checkpoint(FULL)",null).close();File src=getDatabasePath("fastrade.db");InputStream in=new FileInputStream(src);OutputStream out=getContentResolver().openOutputStream(uri);if(out==null)throw new IOException("Impossibile creare backup");copy(in,out);in.close();out.close();toast("Backup completato");}
    private void readBackup(Uri uri)throws Exception{File dst=getDatabasePath("fastrade.db"),tmp=new File(getCacheDir(),"fastrade_restore.db");InputStream in=getContentResolver().openInputStream(uri);if(in==null)throw new IOException("File non leggibile");OutputStream out=new FileOutputStream(tmp);copy(in,out);in.close();out.close();db.close();InputStream bin=new FileInputStream(tmp);OutputStream bout=new FileOutputStream(dst,false);copy(bin,bout);bin.close();bout.close();new File(dst.getPath()+"-wal").delete();new File(dst.getPath()+"-shm").delete();db=new TradeDbHelper(this);toast("Dati ripristinati");showDashboard();}
    private void copy(InputStream in,OutputStream out)throws IOException{byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);out.flush();}
    private void confirmDeleteMovement(long id){new AlertDialog.Builder(this).setTitle("Elimina movimento?").setMessage("Il deposito o prelievo verrà eliminato e il bankroll sarà ricalcolato.").setPositiveButton("Elimina",(d,w)->{db.deleteOperation(id);bankTab=1;showBankroll();}).setNegativeButton("Annulla",null).show();}

    private void showStrategyManager(){page("Gestione Strategie",4);content.addView(action("＋ NUOVA STRATEGIA",GREEN,v->strategyDialog(null)));List<TradeDbHelper.Strategy> list=db.allStrategies(false);if(list.isEmpty()){content.addView(empty("Nessuna strategia personalizzata."));return;}for(TradeDbHelper.Strategy s:list){LinearLayout c=card(SURFACE);LinearLayout top=row();top.addView(text(s.name,14,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));TextView st=text(s.active?"ATTIVA":"OFF",9,Color.WHITE,true);st.setGravity(Gravity.CENTER);st.setBackground(round(s.active?DARKGREEN:Color.DKGRAY,7,0));top.addView(st,new LinearLayout.LayoutParams(dp(56),dp(26)));c.addView(top);if(!s.description.isEmpty())c.addView(text(s.description,10,MUTED,false));c.addView(text("Stake default: "+one.format(s.defaultStakePct)+"%",10,BLUE,true));LinearLayout ac=row();Button edit=smallButton("MODIFICA",BLUE2);edit.setOnClickListener(v->strategyDialog(s));ac.addView(edit,wp());Button tg=smallButton(s.active?"DISATTIVA":"ATTIVA",SURFACE2);tg.setOnClickListener(v->{db.updateStrategy(s.id,s.name,s.description,s.defaultStakePct,!s.active);showStrategyManager();});ac.addView(tg,wp());c.addView(ac);content.addView(c);}}
    private void strategyDialog(TradeDbHelper.Strategy old){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);EditText name=input(false,"Nome strategia"),desc=input(false,"Regole / descrizione"),stake=input(true,"2,0");if(old!=null){name.setText(old.name);desc.setText(old.description);stake.setText(one.format(old.defaultStakePct));}box.addView(field("Nome",name));box.addView(field("Descrizione",desc));box.addView(field("Stake default %",stake));new AlertDialog.Builder(this).setTitle(old==null?"Nuova strategia":"Modifica strategia").setView(box).setPositiveButton("Salva",(d,w)->{if(name.getText().toString().trim().isEmpty())return;if(old==null)db.addStrategy(name.getText().toString(),desc.getText().toString(),parse(stake.getText().toString()));else db.updateStrategy(old.id,name.getText().toString(),desc.getText().toString(),parse(stake.getText().toString()),old.active);showStrategyManager();}).setNegativeButton("Annulla",null).show();}

    private List<String> getStrategies(){LinkedHashSet<String> set=new LinkedHashSet<>();Collections.addAll(set,DEFAULT_STRATEGIES);for(TradeDbHelper.Strategy s:db.allStrategies(true))set.add(s.name);return new ArrayList<>(set);}
    private void askStartingBank(){EditText e=input(true,"Starting Bank €");e.setText(String.valueOf(prefs.getFloat("starting_bank",0)));new AlertDialog.Builder(this).setTitle("Starting Bank").setView(e).setPositiveButton("Salva",(d,w)->{prefs.edit().putFloat("starting_bank",(float)parse(e.getText().toString())).apply();showBankroll();}).setNegativeButton("Annulla",null).show();}
    private void confirmDelete(long id){new AlertDialog.Builder(this).setTitle("Elimina operazione?").setMessage("L'operazione verrà rimossa dal diario e dalle statistiche.").setPositiveButton("Elimina",(d,w)->{db.deleteOperation(id);showJournal();}).setNegativeButton("Annulla",null).show();}

    private Stats stats(){Stats s=new Stats();s.startingBank=prefs.getFloat("starting_bank",0);for(TradeDbHelper.Operation o:db.allOperations()){if(isMovement(o)){if(o.result>=0)s.deposits+=o.result;else s.withdrawals+=o.result;continue;}s.totalTrades++;s.totalStake+=o.stakeEur;s.netProfit+=o.result;if(o.result>0)s.wins++;else if(o.result<0)s.losses++;}s.currentBank=s.startingBank+s.deposits+s.withdrawals+s.netProfit;s.winPct=s.totalTrades==0?0:(double)s.wins/s.totalTrades;s.roi=s.totalStake==0?0:s.netProfit/s.totalStake;return s;}
    private boolean isMovement(TradeDbHelper.Operation o){String m=o.market==null?"":o.market;return m.equalsIgnoreCase("DEPOSIT")||m.equalsIgnoreCase("WITHDRAW")||m.equalsIgnoreCase("DEPOSITO")||m.equalsIgnoreCase("PRELIEVO");}
    private List<Double> bankrollSeries(double start,int days){ArrayList<TradeDbHelper.Operation> chronological=new ArrayList<>(db.allOperations());Collections.reverse(chronological);SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY);Calendar today=Calendar.getInstance(Locale.ITALY);zeroTime(today);Calendar first=(Calendar)today.clone();first.add(Calendar.DAY_OF_YEAR,-Math.max(1,days)+1);double bank=start;for(TradeDbHelper.Operation o:chronological){try{Date d=f.parse(o.date);if(d.before(first.getTime()))bank+=o.result;}catch(Exception ignored){}}ArrayList<Double> vals=new ArrayList<>();Calendar day=(Calendar)first.clone();while(!day.after(today)){String ds=f.format(day.getTime());for(TradeDbHelper.Operation o:chronological)if(ds.equals(o.date))bank+=o.result;vals.add(bank);day.add(Calendar.DAY_OF_YEAR,1);}if(vals.size()<2)vals.add(bank);return vals;}
    private List<Double> profitSeries(int days){ArrayList<TradeDbHelper.Operation> chronological=new ArrayList<>(db.allOperations());Collections.reverse(chronological);SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY);Calendar today=Calendar.getInstance(Locale.ITALY);zeroTime(today);Calendar first=(Calendar)today.clone();first.add(Calendar.DAY_OF_YEAR,-Math.max(1,days)+1);double profit=0;for(TradeDbHelper.Operation o:chronological){if(isMovement(o))continue;try{Date d=f.parse(o.date);if(d.before(first.getTime()))profit+=o.result;}catch(Exception ignored){}}ArrayList<Double> vals=new ArrayList<>();Calendar day=(Calendar)first.clone();while(!day.after(today)){String ds=f.format(day.getTime());for(TradeDbHelper.Operation o:chronological)if(!isMovement(o)&&ds.equals(o.date))profit+=o.result;vals.add(profit);day.add(Calendar.DAY_OF_YEAR,1);}if(vals.size()<2)vals.add(profit);return vals;}
    private void zeroTime(Calendar c){c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);}
    private double todayProfit(){String d=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY).format(new Date());double x=0;for(TradeDbHelper.Operation o:db.allOperations())if(d.equals(o.date)&&!isMovement(o))x+=o.result;return x;}
    private int todayTrades(){String d=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY).format(new Date());int n=0;for(TradeDbHelper.Operation o:db.allOperations())if(d.equals(o.date)&&!isMovement(o))n++;return n;}
    private double dayTotal(String date){double x=0;for(TradeDbHelper.Operation o:db.allOperations())if(date.equals(o.date)&&!isMovement(o))x+=o.result;return x;}
    private double weekProfit(){Calendar now=Calendar.getInstance(Locale.ITALY);int wk=now.get(Calendar.WEEK_OF_YEAR),yr=now.get(Calendar.YEAR);SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY);double x=0;for(TradeDbHelper.Operation o:db.allOperations()){try{Calendar c=Calendar.getInstance(Locale.ITALY);c.setTime(f.parse(o.date));if(c.get(Calendar.WEEK_OF_YEAR)==wk&&c.get(Calendar.YEAR)==yr&&!isMovement(o))x+=o.result;}catch(Exception ignored){}}return x;}
    private List<TradeDbHelper.Operation> filteredOps(){List<TradeDbHelper.Operation> all=db.allOperations();if(journalFilter==0)return nonMovement(all);ArrayList<TradeDbHelper.Operation> out=new ArrayList<>();Calendar now=Calendar.getInstance(Locale.ITALY);SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY);for(TradeDbHelper.Operation o:all){if(isMovement(o))continue;try{Calendar c=Calendar.getInstance(Locale.ITALY);c.setTime(f.parse(o.date));boolean ok=journalFilter==1&&sameDay(c,now)||journalFilter==2&&c.get(Calendar.WEEK_OF_YEAR)==now.get(Calendar.WEEK_OF_YEAR)&&c.get(Calendar.YEAR)==now.get(Calendar.YEAR)||journalFilter==3&&c.get(Calendar.MONTH)==now.get(Calendar.MONTH)&&c.get(Calendar.YEAR)==now.get(Calendar.YEAR);if(ok)out.add(o);}catch(Exception ignored){}}return out;}
    private List<TradeDbHelper.Operation> nonMovement(List<TradeDbHelper.Operation> all){ArrayList<TradeDbHelper.Operation> x=new ArrayList<>();for(TradeDbHelper.Operation o:all)if(!isMovement(o))x.add(o);return x;}
    private boolean sameDay(Calendar a,Calendar b){return a.get(Calendar.YEAR)==b.get(Calendar.YEAR)&&a.get(Calendar.DAY_OF_YEAR)==b.get(Calendar.DAY_OF_YEAR);}
    private Map<String,SS> strategyMap(){Map<String,SS> map=new LinkedHashMap<>();for(TradeDbHelper.Operation o:db.allOperations()){if(isMovement(o))continue;String k=o.strategy.isEmpty()?o.market:o.strategy;SS x=map.get(k);if(x==null){x=new SS();map.put(k,x);}x.op++;if(o.result>0)x.win++;else if(o.result<0)x.lose++;x.profit+=o.result;x.stake+=o.stakeEur;}return map;}

    private View goal(String name,double actual,double target){LinearLayout c=card(SURFACE);LinearLayout rr=row();LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.VERTICAL);left.addView(text(name,12,TEXT,true));left.addView(text("Target "+money.format(target)+"  •  Attuale "+money.format(actual),10,MUTED,false));rr.addView(left,new LinearLayout.LayoutParams(0,-2,1));double q=target<=0?0:actual/target;TextView pc=text((int)(q*100)+"%",12,q>=1?GREEN:CYAN,true);rr.addView(pc);c.addView(rr);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(1000);pb.setProgress((int)Math.max(0,Math.min(1000,q*1000)));pb.getProgressDrawable().setColorFilter(q>=1?GREEN:BLUE,android.graphics.PorterDuff.Mode.SRC_IN);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(6));pp.setMargins(0,dp(8),0,0);c.addView(pb,pp);return c;}
    private View kpi(String label,String value,int color){LinearLayout c=card(SURFACE);c.setPadding(dp(11),dp(9),dp(11),dp(9));c.addView(text(label,9,MUTED,false));TextView v=text(value,15,color,true);v.setPadding(0,dp(4),0,0);c.addView(v);return c;}
    private View kpiSpark(String label,String value,int color,int type){LinearLayout c=card(SURFACE);c.setPadding(dp(10),dp(9),dp(10),dp(5));c.addView(text(label,9,MUTED,false));c.addView(text(value,15,color,true));c.addView(new MiniSpark(this,color,type),new LinearLayout.LayoutParams(-1,dp(28)));return c;}
    private TextView section(String s){TextView t=text(s,15,TEXT,true);t.setPadding(dp(2),dp(12),0,dp(7));return t;}
    private View tab(String s,boolean on,View.OnClickListener l){TextView t=text(s,9,on?Color.WHITE:MUTED,false);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(9),dp(8),dp(9));t.setBackground(horizontalGradient(on?BLUE2:SURFACE2,on?CYAN:SURFACE2,9,on?0:LINE));if(l!=null)t.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(2),0,dp(2),dp(7));t.setLayoutParams(p);return t;}
    private View chip(String s,boolean on,View.OnClickListener l){TextView t=text(s,9,on?Color.WHITE:MUTED,false);t.setGravity(Gravity.CENTER);t.setPadding(dp(9),dp(6),dp(9),dp(6));t.setBackground(horizontalGradient(on?BLUE2:SURFACE2,on?Color.rgb(28,153,255):SURFACE2,7,on?0:LINE));if(l!=null)t.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(dp(2),0,dp(2),0);t.setLayoutParams(p);return t;}
    private TextView cell(String s,float size,int color,boolean bold,float weight){TextView t=text(s,size,color,bold);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(2),dp(7),dp(2),dp(7));t.setSingleLine(true);t.setEllipsize(TextUtils.TruncateAt.END);t.setLayoutParams(new LinearLayout.LayoutParams(0,-2,weight));return t;}
    private LinearLayout card(int bg){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(12),dp(11),dp(12),dp(11));l.setBackground(horizontalGradient(bg,Color.rgb(Math.min(255,Color.red(bg)+3),Math.min(255,Color.green(bg)+5),Math.min(255,Color.blue(bg)+8)),16,LINE));l.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(1),dp(4),dp(1),dp(5));l.setLayoutParams(p);return l;}
    private Button action(String s,int color,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTypeface(Typeface.create("sans",Typeface.BOLD));b.setBackground(horizontalGradient(color,color==GREEN?Color.rgb(17,180,125):CYAN,13,0));b.setOnClickListener(l);b.setElevation(dp(3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(dp(1),dp(7),dp(1),dp(4));b.setLayoutParams(p);return b;}
    private Button smallButton(String s,int color){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(round(color,10,LINE));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(42));p.setMargins(dp(2),dp(3),dp(2),dp(2));b.setLayoutParams(p);return b;}
    private EditText input(boolean number,String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(119,145,166));e.setTextColor(TEXT);e.setTextSize(12);e.setPadding(dp(12),dp(7),dp(12),dp(7));e.setBackground(horizontalGradient(SURFACE2,Color.rgb(12,29,44),11,LINE));if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);e.setMinHeight(dp(44));return e;}
    private Spinner spinner(String[] items){Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,items){@Override public View getView(int p,View v,ViewGroup parent){TextView t=(TextView)super.getView(p,v,parent);t.setTextColor(TEXT);t.setTextSize(12);t.setPadding(dp(10),0,dp(10),0);return t;}@Override public View getDropDownView(int p,View v,ViewGroup parent){TextView t=(TextView)super.getDropDownView(p,v,parent);t.setTextColor(Color.BLACK);return t;}};s.setAdapter(a);s.setBackground(horizontalGradient(SURFACE2,Color.rgb(12,29,44),11,LINE));s.setPadding(dp(4),0,dp(4),0);return s;}
    private View field(String label,View v){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);TextView lab=text(label,9,MUTED,true);lab.setPadding(dp(2),dp(1),0,dp(4));l.addView(lab);l.addView(v,new LinearLayout.LayoutParams(-1,dp(44)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));l.setLayoutParams(p);return l;}
    private View fieldMini(String label,View v){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);TextView lab=text(label,9,MUTED,true);lab.setPadding(dp(2),0,0,dp(3));l.addView(lab);l.addView(v,new LinearLayout.LayoutParams(-1,dp(44)));return l;}
    private TextView empty(String s){TextView t=text(s,12,MUTED,false);t.setGravity(Gravity.CENTER);t.setPadding(dp(20),dp(34),dp(20),dp(34));return t;}
    private TextView text(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));return t;}
    private GradientDrawable round(int fill,int radius,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));if(stroke!=0)g.setStroke(dp(1),stroke);return g;}
    private GradientDrawable horizontalGradient(int a,int b,int radius,int stroke){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{a,b});g.setCornerRadius(dp(radius));if(stroke!=0)g.setStroke(dp(1),stroke);return g;}
    private GradientDrawable verticalGradient(int a,int b){return new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{a,b});}
    private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);return r;}
    private LinearLayout.LayoutParams wp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(2),0,dp(2),0);return p;}
    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private String sign(double x){return x>=0?"+ ":"- ";}
    private double parse(String s){if(s==null||s.trim().isEmpty())return 0;String v=s.trim().replace(" ","");if(v.contains(",")&&v.contains(".")){if(v.lastIndexOf(',')>v.lastIndexOf('.'))v=v.replace(".","").replace(',', '.');else v=v.replace(",","");}else v=v.replace(',', '.');try{return Double.parseDouble(v);}catch(Exception e){return 0;}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

    private static class Stats{double startingBank,currentBank,deposits,withdrawals,netProfit,totalStake,winPct,roi;int wins,losses,totalTrades;}
    private static class SS{int op,win,lose;double profit,stake;}
    private static class NavItem{LinearLayout box;TextView icon,label;int index;NavItem(LinearLayout b,TextView i,TextView l,int x){box=b;icon=i;label=l;index=x;}}

    private class HeroBankCard extends View{
        private final Stats s;private final Paint p=new Paint(1);HeroBankCard(Context c,Stats st){super(c);s=st;setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();RectF r=new RectF(0,0,w,h);Paint bg=new Paint(1);bg.setShader(new LinearGradient(0,0,w,h,Color.rgb(5,55,89),Color.rgb(4,27,48),Shader.TileMode.CLAMP));c.drawRoundRect(r,dp(18),dp(18),bg);Paint stroke=new Paint(1);stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeWidth(dp(1));stroke.setColor(Color.rgb(22,92,135));c.drawRoundRect(r,dp(18),dp(18),stroke);Paint glow=new Paint(1);glow.setShader(new RadialGradient(w*.82f,h*.2f,w*.5f,Color.argb(95,0,255,185),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawRoundRect(r,dp(18),dp(18),glow);
            p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setColor(Color.rgb(205,230,245));p.setTextSize(dp(11));c.drawText("CURRENT BANK",dp(16),dp(28),p);p.setColor(TEXT);p.setTextSize(dp(31));c.drawText(money.format(s.currentBank),dp(16),dp(68),p);p.setColor(s.netProfit>=0?GREEN:RED);p.setTextSize(dp(13));String change=sign(s.netProfit)+money.format(Math.abs(s.netProfit))+"   ("+(s.startingBank==0?"0,0%":pct.format(s.netProfit/s.startingBank))+")";c.drawText(change,dp(16),dp(94),p);
            List<Double> vals=bankrollSeries(s.startingBank,30);if(vals.size()>1){double min=Collections.min(vals),max=Collections.max(vals);if(max-min<1)max=min+1;Path path=new Path();float L=w*.48f,R=w-dp(15),T=h*.36f,B=h-dp(16);for(int i=0;i<vals.size();i++){float x=L+(R-L)*i/(vals.size()-1f);float y=(float)(B-(vals.get(i)-min)/(max-min)*(B-T));if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}Paint line=new Paint(1);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(dp(2.2f));line.setColor(GREEN);line.setShadowLayer(dp(8),0,0,Color.argb(110,0,255,170));c.drawPath(path,line);Paint pt=new Paint(1);pt.setColor(CYAN);c.drawCircle(R,(float)(B-(vals.get(vals.size()-1)-min)/(max-min)*(B-T)),dp(3),pt);}
        }
    }

    private class MiniSpark extends View{private final int color,type;private final Paint p=new Paint(1);MiniSpark(Context c,int col,int t){super(c);color=col;type=t;}@Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();Path path=new Path();float[] ys=type==0?new float[]{.82f,.72f,.78f,.60f,.64f,.48f,.51f,.32f,.38f,.20f}:type==1?new float[]{.70f,.55f,.64f,.47f,.52f,.30f,.35f,.24f,.29f,.14f}:new float[]{.55f,.62f,.50f,.58f,.42f,.46f,.34f,.39f,.27f,.31f};for(int i=0;i<ys.length;i++){float x=dp(2)+(w-dp(4))*i/(ys.length-1f),y=h*ys[i];if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.5f));p.setColor(color);c.drawPath(path,p);}}

    private class BankrollChart extends View{
        private final List<Double> vals; private final int days; private final boolean callout; private final Paint p=new Paint(1),grid=new Paint(1),label=new Paint(1);
        BankrollChart(Context c,List<Double> v,int d,boolean co){super(c);vals=v;days=d;callout=co;grid.setColor(Color.rgb(25,55,73));grid.setStrokeWidth(dp(1));p.setStrokeWidth(dp(2.2f));p.setStyle(Paint.Style.STROKE);p.setColor(BLUE);p.setStrokeCap(Paint.Cap.ROUND);label.setColor(MUTED);label.setTextSize(dp(8));setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();float L=dp(38),R=w-dp(10),T=dp(14),B=h-dp(28);for(int i=0;i<4;i++){float y=T+(B-T)*i/3f;c.drawLine(L,y,R,y,grid);}if(vals==null||vals.size()<2)return;double min=Collections.min(vals),max=Collections.max(vals);double pad=Math.max(1,(max-min)*.15);min-=pad;max+=pad;label.setTextSize(dp(8));for(int i=0;i<4;i++){double v=max-(max-min)*i/3d;String s=v>=1000?one.format(v/1000d)+"k":String.valueOf((int)v);c.drawText(s,dp(2),T+(B-T)*i/3f+dp(3),label);}Path path=new Path();for(int i=0;i<vals.size();i++){float x=L+(R-L)*i/(vals.size()-1f);float y=(float)(B-(vals.get(i)-min)/(max-min)*(B-T));if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}Paint fill=new Paint(1);fill.setShader(new LinearGradient(0,T,0,B,Color.argb(105,25,135,255),Color.TRANSPARENT,Shader.TileMode.CLAMP));Path area=new Path(path);area.lineTo(R,B);area.lineTo(L,B);area.close();c.drawPath(area,fill);p.setShadowLayer(dp(8),0,0,Color.argb(90,25,135,255));c.drawPath(path,p);p.clearShadowLayer();float ly=(float)(B-(vals.get(vals.size()-1)-min)/(max-min)*(B-T));Paint pt=new Paint(1);pt.setColor(GREEN);pt.setShadowLayer(dp(7),0,0,GREEN);c.drawCircle(R,ly,dp(3.5f),pt);pt.clearShadowLayer();Calendar end=Calendar.getInstance(Locale.ITALY),mid=(Calendar)end.clone(),start=(Calendar)end.clone();start.add(Calendar.DAY_OF_YEAR,-days+1);mid.add(Calendar.DAY_OF_YEAR,-days/2);SimpleDateFormat df=new SimpleDateFormat(days>=365?"MMM yy":"d MMM",Locale.ITALY);String a=df.format(start.getTime()),m=df.format(mid.getTime()),z=df.format(end.getTime());c.drawText(a,L,B+dp(18),label);float mw=label.measureText(m);c.drawText(m,(L+R)/2-mw/2,B+dp(18),label);float zw=label.measureText(z);c.drawText(z,R-zw,B+dp(18),label);if(callout){String v=money.format(vals.get(vals.size()-1));float tw=label.measureText(v)+dp(22);float bx=Math.max(L,R-tw),by=Math.max(T+dp(4),ly-dp(35));Paint bubble=new Paint(1);bubble.setColor(Color.rgb(13,34,52));c.drawRoundRect(new RectF(bx,by,R,by+dp(28)),dp(7),dp(7),bubble);label.setColor(TEXT);label.setTextSize(dp(8.5f));c.drawText(v,bx+dp(9),by+dp(18),label);label.setColor(MUTED);}}
    }

    private class DualLineChart extends View{private final List<Double> bank,profit;private final int days;DualLineChart(Context c,List<Double>b,List<Double>p,int d){super(c);bank=b;profit=p;days=d;setLayerType(View.LAYER_TYPE_SOFTWARE,null);}@Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),L=dp(36),R=w-dp(10),T=dp(28),B=h-dp(28);Paint grid=new Paint(1);grid.setColor(Color.rgb(25,55,73));for(int i=0;i<4;i++){float y=T+(B-T)*i/3f;c.drawLine(L,y,R,y,grid);}drawSeries(c,bank,L,R,T,B,BLUE,true);drawSeries(c,profit,L,R,T,B,GREEN,false);Paint lab=new Paint(1);lab.setTextSize(dp(8));lab.setColor(MUTED);lab.setTypeface(Typeface.create("sans",Typeface.NORMAL));c.drawText("● Bankroll",L,T-dp(9),lab);lab.setColor(GREEN);c.drawText("● Profitto",L+dp(72),T-dp(9),lab);Calendar end=Calendar.getInstance(Locale.ITALY),start=(Calendar)end.clone();start.add(Calendar.DAY_OF_YEAR,-days+1);SimpleDateFormat df=new SimpleDateFormat(days>=365?"MMM yy":"d MMM",Locale.ITALY);lab.setColor(MUTED);c.drawText(df.format(start.getTime()),L,B+dp(18),lab);String z=df.format(end.getTime());c.drawText(z,R-lab.measureText(z),B+dp(18),lab);}
        private void drawSeries(Canvas c,List<Double>vals,float L,float R,float T,float B,int col,boolean fillIt){if(vals==null||vals.size()<2)return;double min=Collections.min(vals),max=Collections.max(vals);if(Math.abs(max-min)<1)max=min+1;Path path=new Path();for(int i=0;i<vals.size();i++){float x=L+(R-L)*i/(vals.size()-1f),y=(float)(B-(vals.get(i)-min)/(max-min)*(B-T));if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}if(fillIt){Paint fill=new Paint(1);fill.setShader(new LinearGradient(0,T,0,B,Color.argb(65,25,135,255),Color.TRANSPARENT,Shader.TileMode.CLAMP));Path a=new Path(path);a.lineTo(R,B);a.lineTo(L,B);a.close();c.drawPath(a,fill);}Paint line=new Paint(1);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(dp(2));line.setColor(col);line.setStrokeCap(Paint.Cap.ROUND);c.drawPath(path,line);}}

    private class ProfitBars extends View{private final List<Map.Entry<String,SS>> entries=new ArrayList<>();ProfitBars(Context c,Map<String,SS> m){super(c);entries.addAll(m.entrySet());Collections.sort(entries,(a,b)->Double.compare(Math.abs(b.getValue().profit),Math.abs(a.getValue().profit)));if(entries.size()>7)entries.subList(7,entries.size()).clear();}@Override protected void onDraw(Canvas c){super.onDraw(c);Paint p=new Paint(1),lab=new Paint(1);lab.setTextSize(dp(9));lab.setColor(MUTED);float w=getWidth(),row=dp(31),top=dp(10),left=dp(95),right=w-dp(16);double max=1;for(Map.Entry<String,SS>e:entries)max=Math.max(max,Math.abs(e.getValue().profit));for(int i=0;i<entries.size();i++){Map.Entry<String,SS>e=entries.get(i);float y=top+i*row;String name=e.getKey();if(name.length()>16)name=name.substring(0,15)+"…";c.drawText(name,dp(8),y+dp(18),lab);float len=(float)((right-left)*Math.abs(e.getValue().profit)/max);p.setColor(e.getValue().profit>=0?GREEN:RED);c.drawRoundRect(new RectF(left,y+dp(7),left+len,y+dp(20)),dp(5),dp(5),p);lab.setColor(TEXT);String v=money.format(e.getValue().profit);c.drawText(v,Math.min(right-lab.measureText(v),left+len+dp(6)),y+dp(18),lab);lab.setColor(MUTED);}}}

    private class DonutCard extends View{private final List<Map.Entry<String,SS>> entries=new ArrayList<>();DonutCard(Context c,Map<String,SS> m){super(c);entries.addAll(m.entrySet());}@Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),cx=dp(88),cy=h/2f,rad=dp(57);double total=0;for(Map.Entry<String,SS>e:entries)if(e.getValue().profit>0)total+=e.getValue().profit;Paint p=new Paint(1);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(18));p.setStrokeCap(Paint.Cap.BUTT);int[] cols={BLUE,GREEN,CYAN,GOLD,PURPLE,Color.rgb(112,165,212)};float start=-90;int idx=0;for(Map.Entry<String,SS>e:entries){if(e.getValue().profit<=0)continue;float sweep=total<=0?0:(float)(360d*e.getValue().profit/total);p.setColor(cols[idx%cols.length]);c.drawArc(new RectF(cx-rad,cy-rad,cx+rad,cy+rad),start,sweep,false,p);start+=sweep;idx++;}Paint lab=new Paint(1);lab.setTypeface(Typeface.create("sans",Typeface.BOLD));lab.setTextAlign(Paint.Align.CENTER);lab.setColor(TEXT);lab.setTextSize(dp(13));c.drawText(money.format(total),cx,cy-dp(2),lab);lab.setTextSize(dp(8));lab.setColor(MUTED);c.drawText("Profitto Totale",cx,cy+dp(14),lab);lab.setTextAlign(Paint.Align.LEFT);float x=dp(170),y=dp(26);idx=0;for(Map.Entry<String,SS>e:entries){if(e.getValue().profit<=0)continue;if(y>h-dp(16))break;p.setStyle(Paint.Style.FILL);p.setColor(cols[idx%cols.length]);c.drawCircle(x,y,dp(4),p);lab.setColor(TEXT);lab.setTextSize(dp(9));String name=e.getKey();if(name.length()>15)name=name.substring(0,14)+"…";c.drawText(name,x+dp(10),y+dp(3),lab);lab.setColor(MUTED);String share=total<=0?"0%":((int)Math.round(100*e.getValue().profit/total))+"%";c.drawText(share,w-dp(38),y+dp(3),lab);y+=dp(24);idx++;}}}

    private class WaveDecoration extends View{WaveDecoration(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}@Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();int[] cols={CYAN,BLUE,PURPLE};for(int k=0;k<3;k++){Path path=new Path();path.moveTo(0,h*(.75f-k*.08f));for(int i=0;i<=20;i++){float x=w*i/20f;float y=(float)(h*(.55f-k*.05f)+Math.sin(i*.45+k)*h*.16);path.lineTo(x,y);}Paint p=new Paint(1);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.3f));p.setColor(cols[k]);p.setAlpha(130-k*20);p.setShadowLayer(dp(8),0,0,cols[k]);c.drawPath(path,p);}}}
}
